@url = https://localhost:7203/api
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiODVhNmRjLTBhYTItNDM3ZS1iMmU3LTBmZjdmMzM5YWE2NiIsIm5hbWUiOiJhZG1pbkBwaWNrZXQub2NwaDIzLnRlY2giLCJzdWIiOiJhZG1pbkBwaWNrZXQub2NwaDIzLnRlY2giLCJlbWFpbCI6ImFkbWluQHBpY2tldC5vY3BoMjMudGVjaCIsImp0aSI6Ijk2MWMyYTU4LTY4Y2YtNDUzNS05OWRhLTdhZjA0OGYwMTMzMyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTczMzU2OTQxNSwiZXhwIjoxNzM0MTc0MjE1LCJpYXQiOjE3MzM1Njk0MTUsImlzcyI6Imh0dHBzOi8vcGlja2V0Lm9jcGgyMy50ZWNoLyIsImF1ZCI6Imh0dHBzOi8vcGlja2V0Lm9jcGgyMy50ZWNoLyJ9.6kEo-vRwDc-NNeVQq-ChP1EBAZwZUw37ho84qzHzJPdUzC-13Us1OMVLcKqNGUoghZvdEtsby0mkQIpLGM1odQ
####
POST {{url}}/auth/login HTTP/1.1
Content-Type:application/json

{
    "username":"admin@picket.ocph23.tech",
    "password":"Password@123"
}
####

####Classroom

Get {{url}}/classroom HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

Get {{url}}/classroom/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
POST {{url}}/classroom HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "name": "",
  "departmentId": 1,
  "classRommLeaderId": 1,
  "homeRoomTeacherId": 1
}
####


####
put {{url}}/classroom/3 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id":3,
  "name": "X RPL",
  "departmentId": 1,
  "classRommLeaderId": 1,
  "homeRoomTeacherId": 1
}
####

####
POST {{url}}/classroom/addstudent/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 2
}
####


####
Delete {{url}}/classroom/removestudent/3/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####


