
####Classroom

Get {{url}}/classroom HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

Get {{url}}/classroom/16 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
POST {{url}}/classroom HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "name": "X",
  "departmentId": 1,
  "classRommLeaderId": 2,
  "homeRoomTeacherId": 2
}
####


####
put {{url}}/classroom/16 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "name": "XI",
  "departmentId": 1,
  "classRommLeaderId": 2,
  "homeRoomTeacherId": 1
}
####

####
POST {{url}}/classroom/addstudent/16 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 2
}
####

####
Delete {{url}}/classroom/removestudent/16/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####


