@controller=classroom
####


Get {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

#####


Get {{url}}/{{controller}}/4 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

#####

Get {{url}}/{{controller}}/schoolyear/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
POST {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "name": "XI",
  "departmentId": 2,
  "level": 2,
  "classRommLeaderId": 6,
  "homeRoomTeacherId": 2
}
####



####
POST {{url}}/{{controller}}/classroomfromlast HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "name": "XI",
  "level": 2,
  "classRoomId": 6
}
####


####
put {{url}}/{{controller}}/16 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "name": "XI",
  "departmentId": 1,
  "classRommLeaderId": 2,
  "homeRoomTeacherId": 1
}
####

####
Delete {{url}}/{{controller}}/16 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

####
POST {{url}}/{{controller}}/addstudent/4 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 15
}
####

####
Delete {{url}}/{{controller}}/removestudent/6/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####


