

Get {{url}}/department HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

Get {{url}}/department/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####
POST {{url}}/department HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "name": "Desain Komunikasi dan Visual",
  "initial": "DKV",
  "description": "Jurusan Apa kek"
}
####


put {{url}}/department/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 1,
  "name": "Rekayasa Perangkat Lunak",
  "initial": "RPL",
  "description": "pemograman asad"
}
####


delete {{url}}/department/7 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
