@controller=department


Get {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

Get {{url}}/{{controller}}/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####
POST {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "name": "Desain Komunikasi dan Visual",
  "initial": "DKV",
  "description": "Jurusan Apa kek"
}
####


put {{url}}/{{controller}}/4 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 4,
  "name": "Rekayasa Perangkat Lunak",
  "initial": "RPL",
  "description": "pemograman asad"
}
####


delete {{url}}/{{controller}}/7 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
