@controller = picket
####Piket

Get {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

#####

####Piket

POST {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####Piket

put {{url}}/{{controller}}/5 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 5,
  "date": "2025-01-03",
  "weather": 1,
  "startAt": "08:15:00",
  "endAt": "15:00:00",
  "createdId": 1,
  "createdName": "Yoseph Kungkung",
  "createdNumber": "22222",
  "createAt": "2025-01-03T01:36:20.030386Z",
  "teacherAttendance": null,
  "studentsLateAndComeHomeEarly": []
}

#####

POST {{url}}/{{controller}}/lateandearly HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
    "StudentId":5,
"AtTime":"13:48:17.1764331",
"Description":"ada urusan",
"AttendanceStatus":5,
"LateAndGoHomeEarlyStatus":1}

#####


#####

Delete {{url}}/{{controller}}/lateandearly/25 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


#####