@url = https://picket.ocph23.tech/api
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0OWYxZTRjLWFhM2QtNDY1MC1iZTYzLWY4NzdhODkzZWQzNCIsIm5hbWUiOiJhZG1pbkBwaWNrZXQub2NwaDIzLnRlY2giLCJzdWIiOiJhZG1pbkBwaWNrZXQub2NwaDIzLnRlY2giLCJlbWFpbCI6ImFkbWluQHBpY2tldC5vY3BoMjMudGVjaCIsImp0aSI6ImZkMWE0MmVkLTcwOTgtNGFhNi05NjAxLTlkMGI5OGI3ZWYxMCIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTczMDE4NDI1OSwiZXhwIjoxNzMwNzg5MDU5LCJpYXQiOjE3MzAxODQyNTksImlzcyI6Imh0dHBzOi8vcGlja2V0Lm9jcGgyMy50ZWNoLyIsImF1ZCI6Imh0dHBzOi8vcGlja2V0Lm9jcGgyMy50ZWNoLyJ9.oLNNjIwkIXduQHqnLf1IX_B-T8azm3i4Qz3DNx4LKR4a4OiFsBSXshGDdlG-a05OHUBVushUxhVbae6UY7FmbQ
####
POST {{url}}/auth/login HTTP/1.1
Content-Type:application/json

{
    "username":"admin@picket.ocph23.tech",
    "password":"Password@123"
}
####



####Department

Get {{url}}/department HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
POST {{url}}/department HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "name": "Design Komunikasi Visual",
  "initial": "DKV",
  "description": "MM "
}
####




####SchoolYear

Get {{url}}/schoolyear HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
POST {{url}}/schoolyear HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "year": 2024
}
####

Delete {{url}}/schoolyear/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}
####



####Student

Get {{url}}/student HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
POST {{url}}/student HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "number": "111112",
  "name": "Micha Somole ",
  "gender": 0,
  "placeOfBorn": "Jayapura",
  "dateOfBorn": "2008-03-10",
  "email": "micha@ocph23.tech",
  "description": " Siswa ",
  "userId": ""
}
####


####
put {{url}}/student/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

  {
    "id": 1,
    "number": "000000001",
    "name": "Micha Somole",
    "gender": 0,
    "placeOfBorn": "Jayapura",
    "dateOfBorn": "2008-03-10",
    "email": "micha@ocph23.tech",
    "description": " Siswa ",
    "userId": "c5e78b36-b8a7-42e7-9e04-0e00350c3c6f"
  }
####



####Teacher

Get {{url}}/teacher HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####Teacher

Get {{url}}/teacher/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
####
POST {{url}}/teacher HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "number": "11111",
  "name": "Yoseph ",
  "gender": 0,
  "placeOfBorn": "Jayapura",
  "dateOfBorn": "1979-10-17",
  "email": "ocph23@ocph23.tech",
  "description": " Guru ",
  "userId": ""
}
####


####
put {{url}}/teacher/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
    "id": 1,
    "number": "11111111",
    "name": "Yoseph",
    "gender": 0,
    "placeOfBorn": "Jayapura",
    "dateOfBorn": "1979-10-17",
    "email": "ocph23@ocph23.tech",
    "description": " Guru ",
    "userId": "85f2f727-90d7-4cd1-9802-e7ef1a413166"
  }
####

