@controller = schedule

Get {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

###
Get {{url}}/{{controller}}/byschoolyearId/3 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####
POST {{url}}/{{controller}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "dayOfWeek": 3,
  "teacherId":5
}
####


put {{url}}/{{controller}}/27 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 27,
  "dayOfWeek": 4,
  "teacherId": 1
}
####


delete {{url}}/{{controller}}/5 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
