@url = https://localhost:7203/api/schedule
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1ZjJmNzI3LTkwZDctNGNkMS05ODAyLWU3ZWYxYTQxMzE2NiIsIm5hbWUiOiJvY3BoMjNAb2NwaDIzLnRlY2giLCJzdWIiOiJvY3BoMjNAb2NwaDIzLnRlY2giLCJlbWFpbCI6Im9jcGgyM0BvY3BoMjMudGVjaCIsImp0aSI6ImUzZTMyMjkxLThlOGEtNGQ5ZC1hOTkwLWU4MGI3OTBiMGIyOSIsInJvbGUiOiJUZWFjaGVyIiwibmJmIjoxNzMwMjY4MjI0LCJleHAiOjE3MzA4NzMwMjQsImlhdCI6MTczMDI2ODIyNCwiaXNzIjoiaHR0cHM6Ly9waWNrZXQub2NwaDIzLnRlY2gvIiwiYXVkIjoiaHR0cHM6Ly9waWNrZXQub2NwaDIzLnRlY2gvIn0.q77UMRqU_XvRbNJ3wQDB3512ZdYIhjPdauohHgs2Z2xYwNEJNT8ZZOBOlYFyTGPw9NEk7cZUkT8F_z-P9JMNkw
####

Get {{url}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

###
Get {{url}}/byschoolyearId/4 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

###
Get {{url}}/active HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####
POST {{url}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "dayOfWeek": 3,
  "teacherId": 1
}
####


put {{url}}/7 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 1,
  "dayOfWeek": "3",
  "teacherId": 1
}
####


delete {{url}}/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
