@url = https://picket.ocph23.tech/api/schoolyear
@token = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiODVhNmRjLTBhYTItNDM3ZS1iMmU3LTBmZjdmMzM5YWE2NiIsIm5hbWUiOiJhZG1pbkBwaWNrZXQub2NwaDIzLnRlY2giLCJzdWIiOiJhZG1pbkBwaWNrZXQub2NwaDIzLnRlY2giLCJlbWFpbCI6ImFkbWluQHBpY2tldC5vY3BoMjMudGVjaCIsImp0aSI6Ijg0NTE1M2Q3LWU2Y2MtNGU3NS05ZmYxLTE4NTA0ZWJhYmIzYyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTczNDMxNjc2NiwiZXhwIjoxNzM0OTIxNTY2LCJpYXQiOjE3MzQzMTY3NjYsImlzcyI6Imh0dHBzOi8vcGlja2V0Lm9jcGgyMy50ZWNoLyIsImF1ZCI6Imh0dHBzOi8vcGlja2V0Lm9jcGgyMy50ZWNoLyJ9.jLQMmRF8pfIlDuUhxMNrJ6hDpOd8AlIiwDekjoKRqJDgdlgp--Lwj0U4nMpE9vSrUCxDMfTCJ0qaKG-ut945ZQ



####SchoolYear

Get {{url}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

Get {{url}}/active HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
Get {{url}}/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
####
put {{url}}/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
    "id": 1,
    "year": 2024,
    "semester": 1,
    "semesterName": "Ganjil",
    "name": "2024/2025",
    "actived": true
  }

####

POST {{url}} HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "id": 0,
  "year": 2024
}
####

Delete {{url}}/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}
####



