####

Get {{url}}/teacher HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####

Get {{url}}/teacher/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####

Get {{url}}/teacher/search/yos HTTP/1.1
Content-Type:application/json
Authorization : {{token}}


####
POST {{url}}/teacher HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
  "registerNumber": "11115252",
  "id": 0,
  "name": "Ismail",
  "gender": 0,
  "placeOfBorn": "Papua",
  "dateOfBorn": "1979-02-23",
  "email": "ocph23@gmail",
  "description": "",
  "photo": "",
  "userId": "a27d2aa6-9f2a-44d3-b302-ad6f93bd4a27"
}
####


put {{url}}/teacher/1 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

{
    "registerNumber": "22222",
    "name": "Yoseph Kungkung",
    "gender": 0,
    "placeOfBorn": "Sulawesi",
    "dateOfBorn": "1979-02-23",
    "email": "",
    "description": "Deskripsi Baru",
    "photo": "",
    "userId": ""
  }
####


delete {{url}}/teacher/2 HTTP/1.1
Content-Type:application/json
Authorization : {{token}}

####
